
    group {
        groupbar {
            enabled = true
            font_family = Roboto
            font_size = 14
            font_weight_active = normal
            font_weight_inactive = light
            text_color =
            height = 16
        }
    }