
    group {
        groupbar {
            enabled = true
            font_family = Monaspace Radon
            font_size = 18
            font_weight_active = normal
            font_weight_inactive = light
            text_color = rgb(f5decc)
            height = 16
            indicator_gap = 3
            indicator_height = 3
            rounding = 30
            col.active = rgb(e06f12)
            col.inactive = rgb(12de52)
        }
    }