# ####### Window rules ########
# windowrule = float, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
# windowrule = center, title:^(Open File)(.*)$
# windowrule = center, title:^(Select a File)(.*)$
# windowrule = center, title:^(Choose wallpaper)(.*)$
# windowrule = center, title:^(Open Folder)(.*)$
# windowrule = center, title:^(Save As)(.*)$
# windowrule = center, title:^(Library)(.*)$
# windowrule = center, title:^(File Upload)(.*)$


# Picture-in-Picture
windowrulev2 = keepaspectratio, title:^(Picture(-| )in(-| )[Pp]icture)$
windowrulev2 = opacity 1, title:^(Picture(-| )in(-| ) [Pp]icture)$
windowrulev2 = move 73% 72%,title:^(Picture(-| )in(-| )[Pp]icture)$
windowrulev2 = size 25%, title:^(Picture(-| )in(-| )[Pp]icture)$
windowrulev2 = float, title:^(Picture(-| )in(-| )[Pp]icture)$
windowrulev2 = pin, title:^(Picture(-| )in(-| )[Pp]icture)$
windowrulev2 = tag +fleebravely*, title:^(Picture(-| )in(-| )[Pp]icture)$

windowrulev2 = tag +freebravely*, pinned:1


#Terminal opacity
windowrulev2 = opacity 0.5, class:^(Alacritty)$
windowrulev2 = opacity 0.5, class:^(kitty)$
windowrulev2 = opacity 0.5, class:^(foot)$
windowrulev2 = opacity 0.1, class:^(ghostty)$


# Dialogs
windowrule=float,title:^(Open File)(.*)$
windowrule=float,title:^(Select a File)(.*)$
windowrule=float,title:^(Choose wallpaper)(.*)$
windowrule=float,title:^(Open Folder)(.*)$
windowrule=float,title:^(Save As)(.*)$
windowrule=float,title:^(Library)(.*)$
windowrule=float,title:^(File Upload)(.*)$

# Tearing
windowrule=immediate, title:.*\.exe
windowrulev2=immediate,class:(steam_app)

# Quickshell
layerrule = match:namespace quickshell, blur 1
