# ####### Window rules ########
# windowrule = opacity 0.89 override 0.89 override, .* # Applies transparency to EVERY WINDOW
windowrulev2 = tile, class:(dev.warp.Warp)
windowrulev2 = float, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
# windowrule = center, title:^(Open File)(.*)$
# windowrule = center, title:^(Select a File)(.*)$
# windowrule = center, title:^(Choose wallpaper)(.*)$
# windowrule = center, title:^(Open Folder)(.*)$
# windowrule = center, title:^(Save As)(.*)$
# windowrule = center, title:^(Library)(.*)$
# windowrule = center, title:^(File Upload)(.*)$


windowrule = float, title:^(LM Studio)$
# windowrule = pin, ^(LM Studio)$
windowrule = move 15px 55px, title:^(LM Studio)$
windowrule = size 770px 1015px, title:^(LM Studio)$

windowrule = float, title:^(Chromium)$
#windowrule = pin, ^(Chromium)$
windowrule = move 15px 55px, title:^(Chromium)$
windowrule = size 500px 1015px, title:^(Chromium)$

# Picture-in-Picture
windowrulev2 = keepaspectratio, title:^(Picture(-| )in(-| )[Pp]icture)$
windowrulev2 = opacity 1, title:^(Picture(-| )in(-| ) [Pp]icture)$
windowrulev2 = move 73% 72%,title:^(Picture(-| )in(-| )[Pp]icture)$ 
windowrulev2 = size 25%, title:^(Picture(-| )in(-| )[Pp]icture)$
windowrulev2 = float, title:^(Picture(-| )in(-| )[Pp]icture)$
windowrulev2 = pin, title:^(Picture(-| )in(-| )[Pp]icture)$
windowrulev2 = tag +fleebravely*, title:^(Picture(-| )in(-| )[Pp]icture)$

windowrulev2 = tag +freebravely*, pinned:1


#Terminal opacity
#windowrulev2 = opacity 0.5, class:^(Alacritty)$
#windowrulev2 = opacity 0.5, class:^(kitty)$
#windowrulev2 = opacity 0.5, class:^(foot)$
#windowrulev2 = opacity 0.1, class:^(ghostty)$


# Dialogs
# windowrule=float,title:^(Open File)(.*)$
# windowrule=float,title:^(Select a File)(.*)$
# windowrule=float,title:^(Choose wallpaper)(.*)$
# windowrule=float,title:^(Open Folder)(.*)$
# windowrule=float,title:^(Save As)(.*)$
# windowrule=float,title:^(Library)(.*)$
# windowrule=float,title:^(File Upload)(.*)$

# Tearing
windowrule=immediate, title:.*\.exe
windowrulev2=immediate,class:(steam_app)

# ags
layerrule = blur, bar
layerrule = ignorealpha [a], bar
layerrule = blur, notifications-popup
layerrule = ignorealpha [a], notifications-popup
layerrule = blur, Notifications
layerrule = ignorealpha [a], Notifications
layerrule = blur, SideBar:
layerrule = ignorealpha [a], SideBar
layerrule = blur, transparent-scrim
layerrule = ignorealpha [a], transparent-scrim
layerrule = blur, control-center
layerrule = ignorealpha [a], control-center
layerrule = blur, weather
layerrule = ignorealpha [a], weather
layerrule = blur, media
layerrule = ignorealpha [a], media
layerrule = blur, osd
layerrule = ignorealpha [a], osd
layerrule = blur, dashboard
layerrule = ignorealpha [a], dashboard
layerrule = blur, app-launcher
layerrule = ignorealpha [a], app-launcher
layerrule = blur, popup-window
layerrule = ignorealpha [a], popup-window
layerrule = blur, transparent-scrim
layerrule = ignorealpha [a], transparent-scrim
layerrule = blur, screenshot
layerrule = ignorealpha [a], screenshot
layerrule = blur, taskBar
layerrule = ignorealpha [a], taskBar
layerrule = blur, opaque-scrim
layerrule = ignorealpha [a], opaque-scrim
windowrule = noblur [on], class:^(opaque-scrim)$
