
general {
    col.active_border = rgb(E06F12)
    col.inactive_border = rgb(12DE52)
    col.nogroup_border_active = rgb(E06F12)
    col.nogroup_border = rgb(12DE52)
}

misc {
    background_color = rgba(FAF9F9FF)
}

decoration {
    rounding = 30
    rounding_power = 1.0
    active_opacity = 1
    inactive_opacity = 0.98
    dim_inactive = true
    dim_strength = 0.05

    blur {
		enabled = true
	    passes = 3
	    size = 10
	    vibrancy = 1
	    contrast = 1.5
	    ignore_opacity = true
    }

    shadow {
    	enabled = false
    }
}
