
misc {
    background_color = rgba(FAF9F9FF)
}

decoration {
    rounding = 30
    rounding_power = 2.0
    active_opacity = 1
    inactive_opacity = 0.95
    dim_inactive = true
    dim_strength = 0.05

    blur {
		enabled = true
	    passes = 3
	    size = 10
	    vibrancy = 1
	    contrast = 1.5
	    ignore_opacity = true
    }

    shadow {
    	enabled = false
    }
}
