# exec = export SLURP_ARGS='-d -c 141D1FBB -b D8E1E444 -s 00000000'

general {
    border_size = 0
    col.active_border = rgb(D21EB1)
    col.inactive_border = rgb(1ED2A5)
    col.nogroup_border_active = rgb(D21EB1)
    col.nogroup_border = rgb(1ED2A5)
}

misc {
    background_color = rgba(FAF9F9FF)
}

decoration {
    rounding = 8
    # enable when hyprland updates
    # rounding_power = 4.0
    active_opacity = 1
    inactive_opacity = 0.9
    dim_inactive = true
    dim_strength = 0.2

    blur {
	enabled = true
    size = 4
    passes = 3
    noise = 0
    vibrancy = 2
    contrast = 2
    brightness = 1.5
    ignore_opacity = true
    }

    shadow {
    	enabled = false
    }
}
